[build]
  command = "yarn build"
  publish = "dist/client"
  functions = "dist/server"

[[redirects]]
  from = "/rsbrepoch"
  to = "/.netlify/functions/game_date"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
